[package]
name = "nautilus-deepx"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "DeepX integration adapter for the Nautilus trading engine"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "nautilus_deepx"
crate-type = ["rlib"]

[features]
default = ["high-precision"]
extension-module = ["pyo3/extension-module", "python"]
python = ["nautilus-model/python", "pyo3", "pyo3-stub-gen"]
high-precision = ["nautilus-model/high-precision"]

[dependencies]
nautilus-model = { workspace = true }

rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ustr = { workspace = true }

pyo3 = { workspace = true, optional = true }
pyo3-stub-gen = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }