# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

from nautilus_trader import infrastructure
from nautilus_trader import model

__all__ = [
    "DEEPX",
    "DEEPX_CLIENT_ID",
    "DEEPX_VENUE",
    "DeepXDataClientConfig",
    "DeepXDataClientFactory",
    "DeepXExecutionClientConfig",
    "DeepXExecutionClientFactory",
    "DeepXHttpReadRetryConfig",
    "DeepXNetworkConfig",
]

DEEPX: str
DEEPX_CLIENT_ID: model.ClientId
DEEPX_VENUE: model.Venue

@typing.final
class DeepXDataClientConfig:
    @property
    def network(self) -> DeepXNetworkConfig: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def websocket_timeout_secs(self) -> int: ...
    def __init__(
        self,
        network: DeepXNetworkConfig | None = None,
        proxy_url: str | None = None,
        http_timeout_secs: int | None = None,
        websocket_timeout_secs: int | None = None,
    ) -> None: ...
    @property
    def has_proxy_url(self) -> bool: ...

@typing.final
class DeepXDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class DeepXExecutionClientConfig:
    @property
    def account_id(self) -> model.AccountId: ...
    @property
    def subaccount_id(self) -> str | None: ...
    @property
    def http_timeout_secs(self) -> int: ...
    @property
    def recovery_blocks_per_range(self) -> int: ...
    @property
    def timestamp_nonce_max_clock_drift_ms(self) -> int: ...
    @property
    def network(self) -> DeepXNetworkConfig: ...
    def __init__(
        self,
        account_id: model.AccountId | None = None,
        subaccount_id: str | None = None,
        private_key: str | None = None,
        proxy_url: str | None = None,
        http_timeout_secs: int | None = None,
        execution_backend: str | None = None,
        recovery_blocks_per_range: int | None = None,
        timestamp_nonce_max_clock_drift_ms: int | None = None,
        postgres_cache_database_config: infrastructure.PostgresConnectOptions | None = None,
        network: DeepXNetworkConfig | None = None,
    ) -> None: ...
    @property
    def has_private_key(self) -> bool: ...
    @property
    def has_proxy_url(self) -> bool: ...
    @property
    def has_postgres_cache_database_config(self) -> bool: ...
    @property
    def execution_backend(self) -> str: ...

@typing.final
class DeepXExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class DeepXHttpReadRetryConfig:
    @property
    def max_retries(self) -> int: ...
    @property
    def initial_delay_ms(self) -> int: ...
    @property
    def max_delay_ms(self) -> int: ...
    @property
    def jitter_ms(self) -> int: ...
    @property
    def operation_timeout_ms(self) -> int: ...
    @property
    def max_elapsed_ms(self) -> int: ...
    def __init__(
        self,
        max_retries: int | None = None,
        initial_delay_ms: int | None = None,
        max_delay_ms: int | None = None,
        jitter_ms: int | None = None,
        operation_timeout_ms: int | None = None,
        max_elapsed_ms: int | None = None,
    ) -> None: ...

@typing.final
class DeepXNetworkConfig:
    @property
    def http_read_retry(self) -> DeepXHttpReadRetryConfig: ...
    def __init__(
        self,
        environment: str | None = None,
        base_url_rest: str | None = None,
        base_urls_rest: typing.Sequence[str] | None = None,
        http_read_retry: DeepXHttpReadRetryConfig | None = None,
        base_url_ws: str | None = None,
        base_url_rpc: str | None = None,
        base_url_rpc_submission: str | None = None,
        base_url_rpc_watch: str | None = None,
        base_url_rpc_recovery: str | None = None,
    ) -> None: ...
    @property
    def environment(self) -> str: ...
